baseURL = 'http://ragoragino.dev'
languageCode = 'en-us'
title = 'In the Mood for Programming'
theme = 'paper'
sectionPagesMenu = "main"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'ragoragino'               # twitter.com/YOUR_TWITTER_ID
  github = 'ragoragino'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'rastislav-kisel-3a2151112/'             # linkedin.com/in/YOUR_LINKEDIN_ID
  goodreads = 'ragoragino'
  rss = false                                # show rss icon

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "ltr"                         # RTL support for Right-to-left languages


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "essays"
    name = "Essays"
    url = "/essays/"
    weight = 10
  [[menu.main]]
    identifier = "tech"
    name = "Tech"
    url = "/tech/"
    weight = 10